### PR TITLE
Changed fold_value_biases method to be able to handle multi-gpu. 

### PR DESCRIPTION
**Pull request by Heigke**
Changed fold_value_biases method to be able to handle multi-gpu. Send all layers to same device.

# Description

When using hooked transformer in this way: 
model = HookedTransformer.from_pretrained("microsoft/Phi-3-mini-4k-instruct",cache_dir="/mnt/hdd1",device_map="auto")
I got an error saying:
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 an│
d cpu! See image below refering to the fold_value_biases method.
Screenshot from 2024-08-07 13-07-23
I thereafter changed the method so that all layers are on the same device. See below.
Before change:
Screenshot from 2024-08-07 13-09-07
And after change:
Screenshot from 2024-08-07 13-10-26

And loading the model with device_map="auto" works after this but please double check that it works for more general cases that you can foresee. Thanks!

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Screenshots
Please attach before and after screenshots of the change if applicable.

# Checklist:

- [x ] I have commented my code, particularly in hard-to-understand areas
- [ -] I have made corresponding changes to the documentation
- [ -] My changes generate no new warnings
- [ -] I have added tests that prove my fix is effective or that my feature works
- [ x] New and existing unit tests pass locally with my changes
- [ x] I have not rewritten tests relating to key interfaces which would affect backward compatibility

### CODE REVIEW

**Comment by Heigke** [comment]
Second commit reformatted hookedtransformer with black

**Comment by bryce13950** [comment]
I am not sure if we are going to accept this unfortunately. At the moment, multi-GPU support is in need of improvement, but the thing to do is track what needs to be on the same GPU, and make sure the layers that needs to be on the same GPU are on the same GPU. Multi-GPU support is currently being overhauled to do this, and to select which GPU to put something on based on available memory in a central point. This change seems like it may move us further away from having that bit of logic centralized, since we are interacting directly with the devices in an additional point instead of the point where all of the loading currently happens. I will keep this open a bit for consideration, and for anyone that may want to use this for the time being. If you are interested in helping with general multi-GPU improvement, let me know. There are things that can be done that would help get that project wrapped up.

**Comment by Heigke** [comment]
﻿Hey Bruce,
Thanks for reaching out and for your very sincere and thorough explanation! 
This was my first pull request ever(!) to an open source project and I expected that this was not the root of the problem like you say but I gave it a shot in case it would be helpful for someone so no worries for declining. Hey we got in contact and I would love to try and help democratising understanding of ai models so something came out of it! 
I am not the most experienced developer but extremely passionate about human and AI “brains”, I have been in contact with Joseph Bloom from SAE Lens and neuronpedia and we will talk next week! I don’t know if you know each other but we can probably chat together later if you want and we find some common goal. 

So please share what need to be done and who is in charge and once again thanks! 

Cheers 
Eric Bergvall

**Comment by bryce13950** [comment]
Hey Eric, why don't you jump on the slack channel https://join.slack.com/t/opensourcemechanistic/shared_invite/zt-2ompllv29-LMAXMuiIQF4zd1YsNsnFSw. I am happy to work with you on finding something that needs to be done. If you are interested in helping with this issue, you could take a stab at writing a test for the current work in progress for distributing models across multiple GPUs. I got to the point where I was selecting a device based on the most available amount of memory, and at that point I received the error which you received. A system needs to be put in place to resolve that issue, but the calculations for finding the best available device based on available memory are on a branch, and that needs to be tested properly. Message me on Slack, and I am happy to walk you through a few of the high priorities. Memory uage is currently a major priority for TransformerLens, which is also having a great effect on SAELens.

**Pull request closed without merging**
