### PR TITLE
Add support for Phi-3

### PR DESCRIPTION
**Pull request by slash3g**
# Description

This pull request adds support for [Phi-3](https://huggingface.co/microsoft/Phi-3-mini-4k-instruct-gguf), the latest open-weights model from Microsoft.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [X] I have not rewritten tests relating to key interfaces which would affect backward compatibility

I have not written any new test as I've only added code to parse the config dictionary for Phi-3 and to convert Phi-3's weighs. No other part of TransformerLens has been modified.

### CODE REVIEW

**Comment by neelnanda-io** [comment]
Thanks for adding this! Can you verify that the loss and log probs are (approximately) the same between the TL model and HuggingFace on some sample text, and report how big the discrepancy is? There's often weird unexpected BS there, unfortunately, so it's important to check.

**Comment by slash3g** [comment]
The only two differences that I could find between HF's Phi3 and TL is that HF evaluates attentions scores without upcasting Q and K to float32 (components.py:551) and that HF's Phi3 uses torch.rsqrt to get the inverse of the square root in RMSNorm, while TL performs the two operations separately (components.py:375). I've run some tests while writing the code and the results between the two models seemed identical. However, I can run some more tests tomorrow to be sure that there is no (large) discrepancy in the outputs.

**Comment by neelnanda-io** [comment]
Thanks!

**Comment by bryce13950** [comment]
@slash3g Thanks for putting this up. Everything looks OK to me from the surface. We have had some issues pop up in the recent past where models that have been merged have not worked with all features of TransformerLens. I want to put together a utility notebook for people to use to test new model submissions that will run through the bulk of TransformerLens features, and I would like to use your PR to set that up. I don't think we are going to need anything from you, and fingers crossed that this model works with all features. If there is anything, I will let you know, but there may be a little bit of a delay for getting this merged simply due to needing to do a bit of work on getting that setup.

**Comment by bryce13950** [comment]
@slash3g Do you mind renaming your branch to something else? I am getting ready to put up a release tomorrow, and I want to get your PR up to date with the pending release to run tests, but I cannot push to your branch with the main TransformerLens repo, since the branch you are merging is named `main`, and that causes conflicting naming issues when trying to push merge commits.

**Comment by slash3g** [comment]
> @slash3g Do you mind renaming your branch to something else? I am getting ready to put up a release tomorrow, and I want to get your PR up to date with the pending release to run tests, but I cannot push to your branch with the main TransformerLens repo, since the branch you are merging is named `main`, and that causes conflicting naming issues when trying to push merge commits.

Sorry for the late response, unfortunately, I was out all day yesterday and didn't check my emails. I renamed the branch to phi3-support, but I just realized it's no longer needed. Thank you so much for your work on merging.

**Pull request merged**
